language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers cmake
install:
  - export PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0:2])')
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - ./bin/build_clBLAS.sh
script:
  - nosetests --verbose --with-coverage --cover-package=hindemith
  - mv .coverage .coverage.1
  - CC=gcc HM_BACKEND=omp nosetests --verbose --with-coverage --cover-package=hindemith
  - mv .coverage .coverage.2
  - coverage combine
deploy:
  provider: pypi
  user: leonardt
  password:
    secure: VaklmzdQNl3sg4u7TyrLsZFoAxjGieFMvO8z30sno8pW0zsn2YNpkpfDO1Qy/5kXnSpjLNcDYHJLlcsV2njhONU/0ER5bHwlqAY+n7XM8M+Yk/KvTk6k6dfsl6+k8G2L4K5cSydaz1erYCU/TYgzviki/9D2vMnDG/jP65vevGU=
  on:
    tags: true
    all_branches: true
after_success:
  - coveralls
  - curl -X POST http://readthedocs.org/build/hindemith
notifications:
  slack: ucb-sejits:cPZxBunxagWZ763mcsIXOV0W
